server:
 port: 5000
spring:
 data:
  mongodb:
   uri: ${MONGO_URI:}
   database: ${MONGO_DB:test}
   auto-index-creation: true
logging:
  level:
    root: WARN
    org.springframework: DEBUG
    com.daiken.workoutprogress: INFO
  file:
    name: ${LOG_FILE:workout-progress.log}
cors:
 allowed_origins: ${CORS_ALLOWED_ORIGINS:}
whitelist:
 allowed_client_id: ${WHITELIST_ALLOWED_CLIENT_ID:}
 allowed_client_secret: ${WHITELIST_ALLOWED_CLIENT_SECRET:}
 allowed_remotes: ${WHITELIST_ALLOWED_REMOTES:}
aws:
 cognito:
  cognitoId: ${AWS_COGNITO_ID:}
  cognitoKey: ${AWS_COGNITO_KEY:}
  userPoolId: ${AWS_COGNITO_USER_POOL_ID:}
  region: ${AWS_COGNITO_REGION:}
graphql:
 servlet:
  enabled: true
  mapping: /graphql
  #  actuator-metrics: true
  corsEnabled: true
  cors:
   allowed-origins: ${CORS_ALLOWED_ORIGINS:}
  exception-handlers-enabled: true
  contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
 tools:
  schema-location-pattern: "/graphql/*.graphqls"
graphiql:
 enabled: ${GRAPHIQL_ENABLED:false}
 mapping: /graphiql
 endpoint:
  graphql: /graphql
#tasks:
# FetchWorkoutsTask:
#  cron: '${FETCHWORKOUTS_TASK_CRON:0 0 0 0 * ?}'
sentry:
 dsn: ${SENTRY_DSN:}
 # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
 # We recommend adjusting this value in production.
 traces-sample-rate: 1.0
app-version:
 check: ${APP_VERSION_CHECK:false}
